export const GET_STOCK_DATA_REQUEST = "GET_STOCK_DATA_REQUEST";
export const GET_STOCK_DATA_SUCCESS = "GET_STOCK_DATA_SUCCESS";
export const GET_STOCK_DATA_FAILURE = "GET_STOCK_DATA_FAILURE";

export const ADD_STOCKS_REQUEST = "ADD_SIGNUP_REQUEST";
export const ADD_STOCKS_SUCCESS = "ADD_SIGNUP_SUCCESS";
export const ADD_STOCKS_FAILURE = "ADD_SIGNUP_FAILURE";

export const DELETE_STOCKS_REQUEST = "DELETE_SIGNUP_REQUEST";
export const DELETE_STOCKS_SUCCESS = "DELETE_SIGNUP_SUCCESS";
export const DELETE_STOCKS_FAILURE = "DELETE_SIGNUP_FAILURE";

